# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 102b8834857931661251470d516502aaa9acc08d04ef871e67c9fde19e63cc75501a57b7c4c9f467a0a45a49f18347f719d346b369d2ecb0d92a9295b5c96b26

test:
  secret_key_base: afa378ba77837ac3a8812bdafef583a73d5199dfbdc055a56c9fab5fa4b63fd8e9d003155e749c28a2913f0eb1aa736c0e063249ff5ed7881e1bf84dfe9b9127

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
